hw05_shapes
aasdhajkshd/home_work_basic pull request #4
Opened 2023-12-30 19:36 UTC by aasdhajkshd

## Домашнее задание №5 «Подсчет площади геометрических фигур»

### Чек-лист студента
Для вывода без ошибок, но внести изменения на строке 76: 
calculateSquareArea() => Area()

Вывод команды с "ошибкой"
```output
$ go run .
Круг: радиус 5.60
Площадь: 98.52

Прямоугольник: ширина 5.20, высота 6.40
Площадь: 33.28

Треугольник: длины сторон 5.0, 7.0, 10.1 
Характеристика: неравносторонний
Площадь: 22.68

2023/12/30 22:19:48 main.Square - ошибка: переданный объект не реализует интерфейс Shape
exit status 1
```

Для примера обработки возможных ошибок при подсчете площадей на экран, метод для треугольника, строка 52, изменена формула для подсчёта 3-х сторон вместо основания и высоты. Если указывать на строке 109 переменную "c" в 12.1, будет выводиться обработки ошибки соотношения сторон.

2023-12-31 05:34 UTC, vladislavmass requested changes
Хорошее начало, круто что попробовали написать максимально функциональный код. Но минус такого подхода в том что массово нарушается принцип единой ответственности из SOLID. А также по сути библиотечный код занимается печатью в консоль и это очень заметно сказывается на производительности в целом

2023-12-31 05:34 UTC, vladislavmass commented on hw05_shapes/main.go
> +	r float64
Экспортируемая структура с экспортируемым методом, но с приватным полем и без конструктора это очень плохое сочетание. Структура вроде и может быть использована в других пакетах, но по факту в других пакетах всегда будет возвращаться площадь круга с радиусом 0

2023-12-31 05:34 UTC, vladislavmass commented on hw05_shapes/main.go
> +type Rectangle struct {
Экспортируемая структура с экспортируемым методом, но с приватным полем и без конструктора это очень плохое сочетание. Структура вроде и может быть использована в других пакетах, но по факту в других пакетах всегда будет возвращаться площадь 0

2023-12-31 05:34 UTC, vladislavmass commented on hw05_shapes/main.go
> +		fmt.Printf("\nХарактеристика: ")
Очень плохая идея выводить какую-либо информацию в в методе Area по 2 причинам.
1) Метод Area не должен отвечать за вывод информации в консоль, если бы он отвечал за вывод информации то назывался бы PrintArea и имел бы иную сигнатуру
2) Когда метод неконтролируемой пишет в консоль это очень плохо для вызываеюшего кода, так как очень быстро наступит момент когда программа будет работать очень долго из за записи в терминал

2023-12-31 05:34 UTC, vladislavmass commented on hw05_shapes/main.go
> +func (t *Triangle) SetTriangleSides(a, b, c float64) { // Setter
Лучше заменить данный метод на конструктор, так как все таки стороны в сушествующем треугольники не изменяются. Если изменить треугольник то это будет уже другой треугольник. И никто не делает Setter на 3 поля, так как в таком случае для обновления 1 поля надо знать текущее значение остальных 2.

2023-12-31 05:34 UTC, vladislavmass commented on hw05_shapes/main.go
> +		if t.a == t.b && t.b == t.c {
Данный функционал никаким образом не относится к функционалу вычисления площади

2023-12-31 18:18 UTC, aasdhajkshd commented
Добрый вечер!
Переделал проект, чтобы однозначно отработать экспортируемую структуру с экспортируемым методом, но с приватным полем (Square), строки 69-76, как и с экспортируемыми переменными (Circle, Triangle, Rectangular). Для этого вынес в ./shapes/pkg.go пакет shapes. в main.go, чтобы практически протестировать результаты. Удалил методы проверки треугольника и упростил заморочки с проверкой его. Здесь можно менять на строке 42 менять значения. Так же проверял различные варинаты ошибок, как panic/recover и другие обработки. Setter и Getter сделал к Square для проверки доступа к пакету shapes из main'а. 
Спасибо за рекомендации и поддержку!

2024-01-01 19:28 UTC, vladislavmass requested changes
Работа стала сильно лучше, но все таки предлагаю включить отключение линтеры и сделать так что бы пайплайн был зеленым с учетом этих линтеров. Есть ряд случаев когда линтеры приходится отключать но этих случаев в данном коде нет

2024-01-01 19:28 UTC, vladislavmass commented on hw05_shapes/main.go
> +		panic("Нужно уменьшить длину стороны с 12.1 на 11.1 и запустить снова...") // to test abnormally terminate the program as critical test condition encountered!
В go не стоит относиться с панике как к обработке ошибка, паника это обычно ситуация при которой программа не может больше продолжать работать и это точно не ошибка уровня бизнес логики.  Паника например это когда отвалилась сеть паника это когда пошли ошибки записи в локальную базу из за проблем с ssd, паника это проблемы с криптографическими функциями. Но в бизнес логике применять панику является плохой практикой.

2024-01-01 19:28 UTC, vladislavmass commented on hw05_shapes/.golangci.yml
> +linters:
линтеры лучше не отключать

2024-01-01 19:28 UTC, vladislavmass commented on hw05_shapes/main.go
> +	var s string
Переменная s явно имеет область видимости больше чем надо лучше ее объявлять внутри `if shapes.ValidateTriangle(a, b, c) {`

2024-01-01 21:33 UTC, aasdhajkshd commented
Спасибо за рекомендации. Исключения убраны, код оптимизирован согласно рекомендациям golangci-lint run.
Прошу посмотрите

2024-01-02 06:22 UTC, vladislavmass approved these changes

2024-01-02 12:03 UTC, merged