hw07_word_counter
aasdhajkshd/home_work_basic pull request #6
Opened 2024-01-16 15:02 UTC by aasdhajkshd

## Домашнее задание №7 «Подсчет слов в тексте»

### Чек-лист студента
- реализована функция countWords
- реализована функция printDupsу для отображения слов и частоту появления в тексте больше 1-го раза
- выполняется удаление их от пунктуации и пробелов перед подсчетом
- unit тест на реализованную функцию сравнения map'ов

2024-01-16 16:02 UTC, vladislavmass requested changes

2024-01-16 16:02 UTC, vladislavmass commented on hw07_word_counter/main.go
> +	s := bufio.NewScanner(strings.NewReader(x))
Превращать строку в ридер и потом делать из нее буферезированый ридер не самая лучшая идея по производительности

2024-01-16 16:02 UTC, vladislavmass commented on hw07_word_counter/main.go
> +		w := strings.ToLower(strings.Trim(s.Text(), "!?,. "))
Знаков препинания явно больше)

2024-01-16 19:59 UTC, aasdhajkshd commented
Да, использование TrimFunc() проще, так как остальные Trim'ы - реализация этой же функции.
Убрал bytes.

2024-01-17 05:01 UTC, vladislavmass approved these changes

2024-01-17 05:30 UTC, merged