hw08_binary_search
aasdhajkshd/home_work_basic pull request #7
Opened 2024-01-22 17:08 UTC by aasdhajkshd

## Домашнее задание №8 «Двоичный поиск»

### Чек-лист студента
- Реализована функция двоичного поиска с использованием пакета bytes
- Напишите юнит тест на реализованную функцию;

Детали в Отус чате.

2024-01-23 18:15 UTC, vladislavmass requested changes
Данные метод не является методом бинарного поиска и не имеет вообще никакого алгоритмического смысла. Суть бинарного поиска в том, что бы найти элемент в массиве за O(log n), Алгоритмическая сложность этого метода явно выше, так как самая быстрая сортирвка отработает за O(n log n). Так же  тут используется ` slices.Index`, чья алгоритмическая сложность O(n). Все это делает метод binarySearch бесполезным.

2024-01-23 18:15 UTC, vladislavmass commented on hw08_binary_search/main.go
> +func binarySearch(r []int, i int) int {
Данные метод не является методом бинарного поиска и не имеет вообще никакого алгоритмического смысла. Суть бинарного поиска в том, что бы найти элемент в массиве за O(log n), Алгоритмическая сложность этого метода явно выше, так как самая быстрая сортирвка отработает за O(n log n). Так же  тут используется ` slices.Index`, чья алгоритмическая сложность O(n). Все это делает метод binarySearch бесполезным.

2024-01-23 20:43 UTC, vladislavmass requested changes
Код работает за линейное время и не является реализацией бинарного поиска, так как в код идет по элементный перебор всех элементов массива.

2024-01-24 15:12 UTC, vladislavmass approved these changes

2024-01-24 15:12 UTC, hungry-honeybadger commented on hw08_binary_search/main.go
> +	lenSlice := len(inputSlice)
Можно сразу при входе проверить может ли вообще искомое число быть в этом массиве. Искать -300 или 600 в массиве от -5 до 5 занятие бесполезное

2024-01-24 15:12 UTC, hungry-honeybadger commented on hw08_binary_search/main.go
> +type BinaryStruct struct {
Со структурой не очень хорошая идея. Так как у нас нет потребности хранить мин и макс значение вне рамок вызова функции, но зато это сделало функцию не потокабезопасной

2024-01-24 15:12 UTC, hungry-honeybadger commented on hw08_binary_search/main.go
> +		fmt.Println("Индекс:", j, "слева:", b.lowValue, "справа:", b.highValue, "значение:", inputSlice[j], "искомое:", searchValue) //nolint:lll
Вывод на экран отладочной печати нужно убирать при сдачи работы.

2024-01-24 15:12 UTC, hungry-honeybadger commented on hw08_binary_search/main.go
> +			nums[v] = true // для понимания количества уникальных чисел
Зачем нужна эта мапа не понятно, если нужен аналог хэш сет из питона то лучше использовать `map[int]strunct{}`

2024-01-24 16:43 UTC, aasdhajkshd commented
Добрый вечер,
Спасибо большое за комментарии. Внёс изменения:
- изменил на map[int]struct{}
- отладочную печать нужно убирал
- структуру убрал, так как в задании речь о финкции
- проверку добавил перед вызовом, так как там добавил вывод текста, что указанное число не является элементом массива. Такой сценарий проверяется только в тестах.

2024-01-27 08:33 UTC, merged